@startuml er
title Modelo ER - Sistema de Gestión de Gimnasio

hide circle


entity USUARIO {
  * id_usuario : integer <<PK>>
  --
  dni : varchar
  nombre : varchar
  apellido : varchar
  email : varchar
  telefono : varchar
  nombre_usuario : varchar
  contrasena : varchar
  tipo_usuario : varchar
}

entity SOCIO {
  * id_usuario : integer <<PK>> <<FK>>
  --
  fecha_nacimiento : date
  estado_fisico : varchar
  objetivo : varchar
  fecha_baja : date
}

entity ENTRENADOR {
  * id_usuario : integer <<PK>> <<FK>>
  --
  especialidad : varchar
  fecha_ingreso : date
}

entity PLAN {
  * id_plan : integer <<PK>>
  --
  nombre : varchar
  precio : decimal
  duracion_dias : integer
}

entity PAGO {
  * id_pago : integer <<PK>>
  --
  monto : decimal
  fecha : date
  fecha_vencimiento : date
  id_socio : integer <<FK>>
  id_plan : integer <<FK>>
}

entity RUTINA {
  * id_rutina : integer <<PK>>
  --
  descripcion : varchar
  fecha_asignacion : date
  id_socio : integer <<FK>>
  id_entrenador : integer <<FK>>
}

entity EJERCICIO {
  * id_ejercicio : integer <<PK>>
  --
  nombre : varchar
  descripcion : varchar
  series : integer
  repeticiones : integer
  id_rutina : integer <<FK>>
}

entity CLASE {
  * id_clase : integer <<PK>>
  --
  nombre : varchar
  descripcion : varchar
  horario : datetime
  duracion : integer
  id_entrenador : integer <<FK>>
}

entity ASISTENCIA {
  * id_asistencia : integer <<PK>>
  --
  fecha_hora : datetime
  id_socio : integer <<FK>>
  id_clase : integer <<FK>>
}


USUARIO ||--o| SOCIO : "es tipo de"
USUARIO ||--o| ENTRENADOR : "es tipo de"
SOCIO ||--o{ PAGO : "realiza"
PLAN ||--o{ PAGO : "se paga con"
SOCIO ||--o{ RUTINA : "tiene"
ENTRENADOR ||--o{ RUTINA : "asigna"
RUTINA ||--o{ EJERCICIO : "contiene"
ENTRENADOR ||--o{ CLASE : "dicta"
SOCIO ||--o{ ASISTENCIA : "registra"
CLASE |o--o{ ASISTENCIA : "recibe"

@enduml
